import React, { useEffect, useState } from "react";
import { fetchAudits, ListDoc } from "../api";
import type { SSEEvent } from "../App";

interface AuditListProps {
  navigate: (href: string) => void;
  lastEvent: SSEEvent | null;
}

const AUDIT_PREFIXES: { prefix: string; label: string }[] = [
  { prefix: "design-", label: "Design audits" },
  { prefix: "spec-",   label: "Spec alignment" },
  { prefix: "impl-",   label: "Implementation" },
  { prefix: "adr-",    label: "ADR audit rounds" },
];

function groupAuditsByPrefix(audits: ListDoc[]): { prefix: string; label: string; items: ListDoc[] }[] {
  const groups: { prefix: string; label: string; items: ListDoc[] }[] = [];
  const remaining = [...audits];

  for (const { prefix, label } of AUDIT_PREFIXES) {
    const items = remaining.filter((a) => {
      const base = a.doc_path.split("/").pop() ?? "";
      return base.startsWith(prefix);
    });
    if (items.length > 0) {
      groups.push({ prefix, label, items });
      items.forEach((item) => {
        const idx = remaining.indexOf(item);
        if (idx !== -1) remaining.splice(idx, 1);
      });
    }
  }

  if (remaining.length > 0) {
    groups.push({ prefix: "other", label: "Other", items: remaining });
  }

  return groups;
}

function auditDisplayName(docPath: string, title: string | null | undefined): string {
  if (title) return title;
  const base = (docPath.split("/").pop() ?? docPath).replace(/\.md$/, "");
  let name = base
    .replace(/^(design|spec|impl)-/, "")
    .replace(/^adr-/, "");
  name = name.replace(/-\d{4}-\d{2}-\d{2}(-r\d+)?$/, "$1");
  name = name.replace(/-/g, " ").trim();
  // Bare numbers like "0051" → "ADR-0051"
  if (/^\d+$/.test(name)) name = `ADR-${name}`;
  // adr0051 → ADR-0051
  name = name.replace(/\badr(\d)/gi, "ADR-$1");
  if (name.length > 0) name = name[0].toUpperCase() + name.slice(1);
  return name || base;
}

function auditDate(docPath: string): string {
  const match = docPath.match(/(\d{4}-\d{2}-\d{2})/);
  return match ? match[1] : "";
}

export default function AuditList({ navigate, lastEvent }: AuditListProps) {
  const [audits, setAudits] = useState<ListDoc[]>([]);
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});

  async function load() {
    try {
      const data = await fetchAudits();
      setAudits(data);
    } catch (err) {
      console.error("AuditList: load failed", err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(); }, []);

  useEffect(() => {
    if (lastEvent?.type === "reindex") load();
  }, [lastEvent]);

  const groups = groupAuditsByPrefix(audits);

  if (loading) {
    return <div style={styles.loading}>Loading…</div>;
  }

  if (audits.length === 0) {
    return (
      <div style={styles.empty}>
        <p style={styles.emptyText}>No audit reports found.</p>
        <p style={styles.emptyHint}>Audit reports are generated by evaluator agents during /feature-change loops.</p>
      </div>
    );
  }

  return (
    <div>
      <h2 style={styles.pageTitle}>Audit Reports</h2>
      <p style={styles.subtitle}>{audits.length} reports from evaluator agents</p>
      <div style={styles.groupsContainer}>
        {groups.map(({ prefix, label, items }) => {
          const isExpanded = expanded[prefix] ?? true;
          return (
            <div key={prefix} style={styles.group}>
              <button
                style={styles.groupHeader}
                onClick={() => setExpanded((prev) => ({ ...prev, [prefix]: !isExpanded }))}
                aria-expanded={isExpanded}
              >
                <span style={styles.groupLabel}>{label}</span>
                <span style={styles.groupCount}>{items.length}</span>
                <span style={styles.chevron}>{isExpanded ? "▾" : "▸"}</span>
              </button>
              {isExpanded && (
                <ul style={styles.list}>
                  {items.map((audit) => (
                    <li key={audit.doc_path} style={styles.item}>
                      <button
                        style={styles.itemLink}
                        onClick={() => navigate(`/audit/${audit.doc_path}`)}
                      >
                        <span style={styles.itemTitle}>
                          {auditDisplayName(audit.doc_path, audit.title)}
                        </span>
                        <span style={styles.itemDate}>
                          {auditDate(audit.doc_path)}
                        </span>
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  pageTitle: {
    fontSize: "1.3rem",
    fontWeight: 700,
    color: "#e2e8f0",
    marginBottom: "0.25rem",
  },
  subtitle: {
    fontSize: "0.85rem",
    color: "#718096",
    marginBottom: "1.5rem",
  },
  groupsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    maxWidth: "800px",
  },
  group: {
    borderRadius: "6px",
    overflow: "hidden",
    border: "1px solid #2d3748",
  },
  groupHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.6rem 1rem",
    background: "#1a1f2e",
    border: "none",
    cursor: "pointer",
    width: "100%",
    textAlign: "left",
    color: "#e2e8f0",
  },
  groupLabel: {
    fontSize: "0.9rem",
    color: "#f6ad55",
    fontWeight: 600,
    flex: 1,
  },
  groupCount: {
    fontSize: "0.75rem",
    color: "#718096",
    background: "#2d3748",
    padding: "0.1em 0.5em",
    borderRadius: "10px",
  },
  chevron: {
    color: "#4a5568",
    fontSize: "0.75rem",
  },
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    background: "#111827",
  },
  item: {
    borderTop: "1px solid #1a1f2e",
  },
  itemLink: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0.5rem 1rem",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#e2e8f0",
    width: "100%",
    textAlign: "left",
  },
  itemTitle: {
    fontSize: "0.85rem",
    color: "#cbd5e0",
    flex: 1,
  },
  itemDate: {
    fontSize: "0.75rem",
    color: "#4a5568",
    flexShrink: 0,
    marginLeft: "1rem",
  },
  loading: {
    color: "#718096",
    padding: "2rem",
    textAlign: "center",
  },
  empty: {
    padding: "3rem",
    textAlign: "center",
  },
  emptyText: {
    color: "#718096",
    fontSize: "1rem",
    marginBottom: "0.5rem",
  },
  emptyHint: {
    color: "#4a5568",
    fontSize: "0.85rem",
  },
};
